/**
 * IDs used in lookups and file paths must be data, never path segments or code.
 * Allows UUID / hex / base64url-style values generated by this app.
 */
const SAFE_STORAGE_ID = /^[A-Za-z0-9._:-]{1,128}$/;

export function sanitizeStorageId(value: string | null | undefined): string | null {
  const trimmed = value?.trim() ?? "";
  if (!trimmed) return null;
  if (trimmed.includes("..") || trimmed.includes("/") || trimmed.includes("\\")) {
    return null;
  }
  if (!SAFE_STORAGE_ID.test(trimmed)) return null;
  return trimmed;
}

export function requireStorageId(value: string, label = "id"): string {
  const safe = sanitizeStorageId(value);
  if (!safe) {
    throw new Error(`Invalid ${label}.`);
  }
  return safe;
}
